### PR TITLE
Port to deno

### PR DESCRIPTION
**Pull request by Supinic**
Yes

### CODE REVIEW

**Comment by GaZaTu** [comment]
maybe

**Review by GaZaTu — APPROVED** [review]

**Review by jprochazk — APPROVED** [review]
lgtm 🚀 🔥 💯 👍 🥇 :trollface:

**Review by EuleHaken — APPROVED** [review]
LGTM

**Comment by Supinic** [comment]
Typescript wizards have given me their approval 👍

**Pull request merged**
